### PR TITLE
initial parse results - 2016 precincts

### PR DESCRIPTION
**Pull request by tamilyn**
Issue #14 

Initial version.  Should the values to normalized/cleaned up?  e.g. party is a 3 letter code (DEM,IND,GRN, etc), some of the office names have spaces in them. 

There was a parse error in the clarity parser in some of the files where the subjurisdiction was Emergency, which required me to test for the existence of a key in the dictionary to keep it from crashing, but otherwise there were no problems.

### CODE REVIEW

**Comment by dwillis** [comment]
@tamilyn Thanks Tami! You don't need to standardize parties, but if there are extraneous spaces in office names removing them would be helpful. I'd love to take a look at the script as well if that's ok, too.

**Comment by tamilyn** [comment]
I'll provide my script here.   Most of the data files had Emergency, Failsafe Provisional, and maybe other nodes that caused the clarify Parser to through an error.     I copied the parser class and modified it to handle some dictionary lookups that were throwing errors.   I added the parser file and data files to a subdirectory.  Not sure if these will be added to this pull or not.

**Comment by tamilyn** [comment]
this has the two files - the patched parser in 'patch.py' and the processing program in 'program.py'.  I manually downloaded the precinct data files.(which are in this directory as well).

https://github.com/tamilyn/openelections-data-sc/tree/master/2016-parser

**Comment by dwillis** [comment]
@tamilyn if you wanted to, you could add your parser changes to the [Clarify repo](https://github.com/openelections/clarify) itself.

**Comment by tamilyn** [comment]
Good idea, I'll do that.

**Pull request merged**
